server:
  port: 80

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: https://itedus.cn

chatgml:
  sdk:
    config:
      # 官网地址 https://open.bigmodel.cn/
      api-host: https://open.bigmodel.cn/
      # 官网申请API-KEY
      api-key: 42e670f4c94232aafa9d2a6666ac286c.nLj8y9ZMex0HvaFB

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
