# /usr/local/bin/docker-compose -f /docs/dev-ops/environment/environment-docker-compose.yml up -d
version: '3'
services:
  # MySQL 8.0.26
  mysql:
    #镜像
    image: mysql:8.0.26
    container_name: mysql
    restart: always
    #环境
    environment:
      #root密码
      MYSQL_ROOT_PASSWORD: 159357
      #数据库
      MYSQL_DATABASE: openAi-data
      #用户
      MYSQL_USER: hzq
      MYSQL_PASSWORD: 123456
      #端口
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
